#program to i/p eight numbers from the user and display all the unique no's once

e=set()
n =input("enter number1:")
e.add(int(n))
n =input("enter number2:")
e.add(int(n))
n =input("enter number3:")
e.add(int(n))
n =input("enter number4:")
e.add(int(n))
n =input("enter number5:")
e.add(int(n))
n =input("enter number6:")
e.add(int(n))
n =input("enter number7:")
e.add(int(n))
n =input("enter number8:")
e.add(int(n))
print(e)